# Generated by Django 5.2.7 on 2025-11-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin nombre', max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], default='perro', max_length=10, verbose_name='Especie')),
                ('genero', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='macho', max_length=10, verbose_name='Género')),
                ('edad', models.PositiveIntegerField(default=1, help_text='Edad en años', verbose_name='Edad')),
                ('tamaño', models.CharField(choices=[('pequeño', 'Pequeño (0-10kg)'), ('mediano', 'Mediano (10-25kg)'), ('grande', 'Grande (25-45kg)'), ('gigante', 'Gigante (+45kg)')], default='mediano', max_length=15, verbose_name='Tamaño')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kg (opcional)', max_digits=5, null=True, verbose_name='Peso')),
                ('color', models.CharField(default='marrón', max_length=100, verbose_name='Color')),
                ('foto', models.ImageField(upload_to='mascotas/', verbose_name='Foto')),
                ('necesidades_especiales', models.BooleanField(default=False, verbose_name='¿Tiene necesidades especiales?')),
                ('descripcion_necesidades', models.TextField(blank=True, null=True, verbose_name='Descripción de necesidades especiales')),
                ('convivencia_animales', models.CharField(choices=[('no', 'No puede convivir con otros animales'), ('misma_especie', 'Solo con animales de su misma especie'), ('cualquier_especie', 'Puede convivir con cualquier animal')], default='no', max_length=20, verbose_name='¿Puede convivir con otros animales?')),
                ('convivencia_ninos', models.CharField(choices=[('si', 'Sí, puede convivir con niños'), ('no', 'No, no puede convivir con niños'), ('mayores', 'Solo con niños mayores (más de 8 años)')], default='no', max_length=10, verbose_name='¿Puede convivir con niños?')),
                ('caracter', models.CharField(default='cariñoso', help_text='Características separadas por comas', max_length=200, verbose_name='Carácter')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción adicional')),
                ('ubicacion', models.CharField(default='Ciudad', max_length=100, verbose_name='Ubicación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascotas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
