# Generated by Django 5.2.6 on 2025-11-14 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], default='perro', max_length=10)),
                ('foto', models.ImageField(upload_to='mascotas/')),
                ('descripcion', models.TextField()),
                ('edad', models.PositiveIntegerField(help_text='Edad en años')),
                ('ubicacion', models.CharField(default='Ciudad', max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
