# Generated by Django 5.2.7 on 2025-11-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.PositiveIntegerField(default=0, help_text='Edad en años', verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato')], default='gato', max_length=10, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='genero',
            field=models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], default='hembra', max_length=10, verbose_name='Género'),
        ),
    ]
