# Generated by Django 5.2.7 on 2025-11-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_alter_mascota_edad_alter_mascota_especie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='convivencia_ninos',
            field=models.CharField(choices=[('si', 'Sí, puede convivir con niños'), ('no', 'No, no puede convivir con niños')], default='no', max_length=10, verbose_name='¿Puede convivir con niños?'),
        ),
    ]
