# Generated by Django 5.2.8 on 2025-11-14 17:46

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilprotectora',
            name='direccion_completa',
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='ambito_geografico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='ano_fundacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='calle_juridica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='calle_refugio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='capacidad_maxima_animales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='cif',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='codigo_postal_juridica',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='codigo_postal_refugio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='direccion_juridica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='direccion_refugio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='num_registro_asociacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='numero_juridica',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='numero_refugio',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='poblacion_juridica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='poblacion_refugio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='proceso_adopcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='requisitos_adopcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='servicios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('recogida', 'Recogida de animales abandonados'), ('alojamiento', 'Alojamiento'), ('esterilizacion', 'Esterilización'), ('localizacion', 'Localización de propietarios'), ('adopcion', 'Adopción')], max_length=57),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='tipo_animal',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato'), ('altres', 'Altres')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='tipo_entidad_juridica',
            field=models.CharField(blank=True, choices=[('asociacion', 'Asociación'), ('fundacion', 'Fundación')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilprotectora',
            name='nucleo_zoologico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
