# Generated by Django 5.2.8 on 2025-11-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_perfilprotectora_direccion_completa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilprotectora',
            name='tipo_animal',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10, null=True),
        ),
    ]
