# Generated by Django 5.2.8 on 2025-11-17 09:06

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_perfilprotectora_tipo_animal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='data_nacimiento',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='necesidades_esp',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='deporte_ofrecible',
            field=models.CharField(blank=True, help_text='Deportes/actividades que se le pueden ofrecer (solo para perros)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='especie',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='necesidades_especiales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nivel_actividad_familiar',
            field=models.CharField(blank=True, choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='preferencias_edad',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cachorro', 'Cachorro'), ('joven', 'Joven'), ('adulto', 'Adulto'), ('senior', 'Senior')], max_length=28),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='preferencias_sexo',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=12),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='preferencias_tamano',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=22),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiempo_en_casa_para_gatos',
            field=models.CharField(blank=True, help_text='Tiempo que pasa en casa (útil para gatos)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='tiene_ninos',
            field=models.BooleanField(default=False),
        ),
    ]
