# Generated by Django 5.2.6 on 2025-11-18 02:28

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_remove_perfilusuario_data_nacimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_domingo_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_domingo_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_jueves_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_jueves_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_lunes_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_lunes_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_martes_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_martes_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_miercoles_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_miercoles_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_sabado_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_sabado_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_viernes_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilprotectora',
            name='horario_viernes_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='casa_acogida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='mascota_actual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfilprotectora',
            name='servicios',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('adopcion', 'Adopción'), ('acogida', 'Acogida temporal'), ('veterinario', 'Veterinario'), ('educacion', 'Educación'), ('rehabilitacion', 'Rehabilitación'), ('transporte', 'Transporte'), ('castracion', 'Castración/Esterilitzación'), ('recogida', 'Recogida')], max_length=84),
        ),
    ]
